export const birdstepTechnology = {
  en: {
    company: "Birdstep Technology",
    role: "Test Automation Evang. & DevOps",
    period: "2014-06–2017-05",
    year: "2014 - 2017",
    description: "Mats took on the task of modernizing the client's development methodology and tackling a serious DevOps challenge, in the form of aggregating a daily influx of billions of IoT events.\n\nCODE QUALITY, BEFORE\nZero test coverage. Developers used text editors instead of IDEs for server products, never wrote a single docstring and lacked peer review procedures. For each new release, the client required several months of regression testing and bug fixing. They also lacked CI/CD and structured release management.\n\nCODE QUALITY, AFTER\nAll code migrated from Mercurial to Bitbucket. All server developers have learned to write unit and integration tests, use IDEs and common coding style, accompany their commits with test cases and actively participate in code review discussions before anything is merged into master/develop. Only a minimum of bugs come back from QA and the release cycle has been reduced to a few weeks.\n\nMats also introduced Continuous Integration & Delivery, with release management according to Gitflow Workflow. Now even a project manager can perform a server upgrade by clicking a few buttons in Bamboo.\n\nDEVOPS CHALLENGE\nOn the DevOps side, Mats worked with Birdstep's analytics product for telecom operators, including:\n\n– Developed new analytics tools in Pandas for CSV reports\n– Replaced visual reporting with new web interface and corresponding backend (95% test coverage)\n– Replaced data collection module with a heavily optimized component that reduced the number of physical servers by 50% and logged detailed KPI values to Kibana (98% test coverage)\n– Developed a mapping solution with statistically generated \"heat maps\" (KDE) as overlays to Google Maps for continuous monitoring of network performance.\n\nOver time, Mats grew into the role as in-house authority on automated server orchestration and configuration management. Towards the end of the assignment, he put a lot of effort into sharing his knowledge with IT/Operations and making Ansible a natural tool in everyday life.",
    technologies: "Cassandra, Python, Nosetests, Sphinx, reST, Bash, MySQL, Redis, RabbitMQ, Elasticsearch, SQLAlchemy, Pandas, Mercurial, Bitbucket/Git, JIRA, Bamboo, PHP, ES5, HTML5, Sencha ExtJS 5, CentOS, Elasticsearch, Logstash, Kibana, Nginx, Ansible, Gunicorn, Flask, Docker, Tomcat, Celery",
    keywords: "Business change, requirements analysis, process development, configuration management, data analysis and reporting"
  },
  sv: {
    company: "Birdstep Technology",
    role: "Test Automation Evang. & DevOps",
    period: "2014-06–2017-05",
    year: "2014 - 2017",
    description: "Mats tog sig an att modernisera kundens utvecklingsmetodik och tackla en rejäl DevOps-utmaning, i form av att aggregera ett dagligt inflöde miljarder IoT-events.\n\nKODKVALITET, FÖRE\nNoll test coverage. Utvecklarna använde texteditorer istället för IDE:er för serverprodukterna, skrev aldrig en enda docstring och saknade peer review-förfarande. För varje ny release till kund krävdes flera månader av regressionstestning och buggfixar. Man saknade också CI-miljö och strukturerad release-hantering.\n\nKODKVALITET, EFTER\nAll kod migrerad från Mercurial till Bitbucket. Alla serverutvecklare har lärt sig skriva enhets- och integrationstester, använder IDE:er och gemensam kodstil, ackompanjerar sina commits med testfall och deltar aktivt i code review-diskussioner innan något mergas in i master/develop. Endast ett minimum av buggar kommer tillbaka från QA och release-cykeln har reducerats till några veckor.\n\nMats införde även Continuous Integration & Delivery, med release-hantering enligt Gitflow Workflow. Nu kan till och med en projektledare genomföra en serveruppgradering genom att klicka på några knappar i Bamboo.\n\nDEVOPS-UTMANINGEN\nPå DevOps-sidan arbetade Mats med Birdsteps analytics-produkt för teleoperatörer, bl.a.\n\n– utvecklade nya analysverktyg i Pandas för CSV-rapporter\n– ersatte den visuella rapporteringen med nytt webbgränssnitt och tillhörande backend (95 % test coverage)\n– ersatte datainsamlingsmodulen med en kraftigt effektiviserad komponent som reducerade antalet fysiska servrar med 50 % och loggade ut detaljerade KPI-värden till Kibana (98 % test coverage)\n– utvecklade en kartlösning med statistiskt genererade \"heat maps\" (KDE) som overlays till Google Maps för löpande övervakning av nätprestanda.\n\nMed tiden växte Mats in i rollen som inhouse-auktoritet på automatiserad server-orkestrering och konfigurationshantering. Mot slutet av uppdraget kom han att lägga mycket engagemang på att dela med sig av kunskapen till IT/Operations och göra Ansible till ett naturligt verktyg i vardagen.",
    technologies: "Cassandra, Python, Nosetests, Sphinx, reST, Bash, MySQL, Redis, RabbitMQ, Elasticsearch, SQLAlchemy, Pandas, Mercurial, Bitbucket/Git, JIRA, Bamboo, PHP, ES5, HTML5, Sencha ExtJS 5, CentOS, Elasticsearch, Logstash, Kibana, Nginx, Ansible, Gunicorn, Flask, Docker, Tomcat, Celery",
    keywords: "Verksamhetsförändring, kravanalys, processutveckling, configuration management, dataanalys och rapportering"
  }
};